/************************************************************************/
/* AthrunArthur 2011.7.1                                               */
/************************************************************************/
#ifndef FFCPP_PARALLEL_REPEAT_H_
#define FFCPP_PARALLEL_REPEAT_H_

#ifndef REPEAT_ENTITY
#define REPEAT_ENTITY
#endif


#define FF_REPEAT(REPEAT_TIMES, REPEAT_ENTITY) FF_REPEAT_I(REPEAT_TIMES, REPEAT_ENTITY)
#define FF_REPEAT_I(REPEAT_TIMES, REPEAT_ENTITY) FF_REPEAT ## REPEAT_TIMES(REPEAT_ENTITY)

//This is for recursive
#define RR_REPEAT(REPEAT_TIMES, REPEAT_ENTITY) RR_REPEAT_I(REPEAT_TIMES, REPEAT_ENTITY)
#define RR_REPEAT_I(REPEAT_TIMES, REPEAT_ENTITY) RR_REPEAT ## REPEAT_TIMES(REPEAT_ENTITY)

#ifndef FF_REPEAT_END_SYM
#define FF_REPEAT_END_SYM
#endif

#ifndef FF_REPEAT_BEGIN_SYM
#define FF_REPEAT_BEGIN_SYM
#endif

#ifndef FF_REPEAT_SEPARATE_SYM
#define FF_REPEAT_SEPARATE_SYM
#endif


#define FF_REPEAT0(REPEAT_ENTITY)
#define FF_REPEAT1(REPEAT_ENTITY) FF_REPEAT0(REPEAT_ENTITY) REPEAT_ENTITY(1)  
#define FF_REPEAT2(REPEAT_ENTITY) FF_REPEAT1(REPEAT_ENTITY) REPEAT_ENTITY(2)  
#define FF_REPEAT3(REPEAT_ENTITY) FF_REPEAT2(REPEAT_ENTITY) REPEAT_ENTITY(3)  
#define FF_REPEAT4(REPEAT_ENTITY) FF_REPEAT3(REPEAT_ENTITY) REPEAT_ENTITY(4)  
#define FF_REPEAT5(REPEAT_ENTITY) FF_REPEAT4(REPEAT_ENTITY) REPEAT_ENTITY(5)  
#define FF_REPEAT6(REPEAT_ENTITY) FF_REPEAT5(REPEAT_ENTITY) REPEAT_ENTITY(6)  
#define FF_REPEAT7(REPEAT_ENTITY) FF_REPEAT6(REPEAT_ENTITY) REPEAT_ENTITY(7)  
#define FF_REPEAT8(REPEAT_ENTITY) FF_REPEAT7(REPEAT_ENTITY) REPEAT_ENTITY(8)  
#define FF_REPEAT9(REPEAT_ENTITY) FF_REPEAT8(REPEAT_ENTITY) REPEAT_ENTITY(9)  
#define FF_REPEAT10(REPEAT_ENTITY) FF_REPEAT9(REPEAT_ENTITY) REPEAT_ENTITY(10)  
#define FF_REPEAT11(REPEAT_ENTITY) FF_REPEAT10(REPEAT_ENTITY) REPEAT_ENTITY(11)  
#define FF_REPEAT12(REPEAT_ENTITY) FF_REPEAT11(REPEAT_ENTITY) REPEAT_ENTITY(12)  
#define FF_REPEAT13(REPEAT_ENTITY) FF_REPEAT12(REPEAT_ENTITY) REPEAT_ENTITY(13)  
#define FF_REPEAT14(REPEAT_ENTITY) FF_REPEAT13(REPEAT_ENTITY) REPEAT_ENTITY(14)  
#define FF_REPEAT15(REPEAT_ENTITY) FF_REPEAT14(REPEAT_ENTITY) REPEAT_ENTITY(15)  
#define FF_REPEAT16(REPEAT_ENTITY) FF_REPEAT15(REPEAT_ENTITY) REPEAT_ENTITY(16)  
#define FF_REPEAT17(REPEAT_ENTITY) FF_REPEAT16(REPEAT_ENTITY) REPEAT_ENTITY(17)  
#define FF_REPEAT18(REPEAT_ENTITY) FF_REPEAT17(REPEAT_ENTITY) REPEAT_ENTITY(18)  
#define FF_REPEAT19(REPEAT_ENTITY) FF_REPEAT18(REPEAT_ENTITY) REPEAT_ENTITY(19)  
#define FF_REPEAT20(REPEAT_ENTITY) FF_REPEAT19(REPEAT_ENTITY) REPEAT_ENTITY(20)  
#define FF_REPEAT21(REPEAT_ENTITY) FF_REPEAT20(REPEAT_ENTITY) REPEAT_ENTITY(21)  
#define FF_REPEAT22(REPEAT_ENTITY) FF_REPEAT21(REPEAT_ENTITY) REPEAT_ENTITY(22)  
#define FF_REPEAT23(REPEAT_ENTITY) FF_REPEAT22(REPEAT_ENTITY) REPEAT_ENTITY(23)  
#define FF_REPEAT24(REPEAT_ENTITY) FF_REPEAT23(REPEAT_ENTITY) REPEAT_ENTITY(24)  
#define FF_REPEAT25(REPEAT_ENTITY) FF_REPEAT24(REPEAT_ENTITY) REPEAT_ENTITY(25)  
#define FF_REPEAT26(REPEAT_ENTITY) FF_REPEAT25(REPEAT_ENTITY) REPEAT_ENTITY(26)  
#define FF_REPEAT27(REPEAT_ENTITY) FF_REPEAT26(REPEAT_ENTITY) REPEAT_ENTITY(27)  
#define FF_REPEAT28(REPEAT_ENTITY) FF_REPEAT27(REPEAT_ENTITY) REPEAT_ENTITY(28)  
#define FF_REPEAT29(REPEAT_ENTITY) FF_REPEAT28(REPEAT_ENTITY) REPEAT_ENTITY(29)  
#define FF_REPEAT30(REPEAT_ENTITY) FF_REPEAT29(REPEAT_ENTITY) REPEAT_ENTITY(30)  
#define FF_REPEAT31(REPEAT_ENTITY) FF_REPEAT30(REPEAT_ENTITY) REPEAT_ENTITY(31)  



#define RR_REPEAT0(REPEAT_ENTITY)
#define RR_REPEAT1(REPEAT_ENTITY) RR_REPEAT0(REPEAT_ENTITY) REPEAT_ENTITY(1)  
#define RR_REPEAT2(REPEAT_ENTITY) RR_REPEAT1(REPEAT_ENTITY) REPEAT_ENTITY(2)  
#define RR_REPEAT3(REPEAT_ENTITY) RR_REPEAT2(REPEAT_ENTITY) REPEAT_ENTITY(3)  
#define RR_REPEAT4(REPEAT_ENTITY) RR_REPEAT3(REPEAT_ENTITY) REPEAT_ENTITY(4)  
#define RR_REPEAT5(REPEAT_ENTITY) RR_REPEAT4(REPEAT_ENTITY) REPEAT_ENTITY(5)  
#define RR_REPEAT6(REPEAT_ENTITY) RR_REPEAT5(REPEAT_ENTITY) REPEAT_ENTITY(6)  
#define RR_REPEAT7(REPEAT_ENTITY) RR_REPEAT6(REPEAT_ENTITY) REPEAT_ENTITY(7)  
#define RR_REPEAT8(REPEAT_ENTITY) RR_REPEAT7(REPEAT_ENTITY) REPEAT_ENTITY(8)  
#define RR_REPEAT9(REPEAT_ENTITY) RR_REPEAT8(REPEAT_ENTITY) REPEAT_ENTITY(9)  
#define RR_REPEAT10(REPEAT_ENTITY) RR_REPEAT9(REPEAT_ENTITY) REPEAT_ENTITY(10)  
#define RR_REPEAT11(REPEAT_ENTITY) RR_REPEAT10(REPEAT_ENTITY) REPEAT_ENTITY(11)  
#define RR_REPEAT12(REPEAT_ENTITY) RR_REPEAT11(REPEAT_ENTITY) REPEAT_ENTITY(12)  
#define RR_REPEAT13(REPEAT_ENTITY) RR_REPEAT12(REPEAT_ENTITY) REPEAT_ENTITY(13)  
#define RR_REPEAT14(REPEAT_ENTITY) RR_REPEAT13(REPEAT_ENTITY) REPEAT_ENTITY(14)  
#define RR_REPEAT15(REPEAT_ENTITY) RR_REPEAT14(REPEAT_ENTITY) REPEAT_ENTITY(15)  
#define RR_REPEAT16(REPEAT_ENTITY) RR_REPEAT15(REPEAT_ENTITY) REPEAT_ENTITY(16)  
#define RR_REPEAT17(REPEAT_ENTITY) RR_REPEAT16(REPEAT_ENTITY) REPEAT_ENTITY(17)  
#define RR_REPEAT18(REPEAT_ENTITY) RR_REPEAT17(REPEAT_ENTITY) REPEAT_ENTITY(18)  
#define RR_REPEAT19(REPEAT_ENTITY) RR_REPEAT18(REPEAT_ENTITY) REPEAT_ENTITY(19)  
#define RR_REPEAT20(REPEAT_ENTITY) RR_REPEAT19(REPEAT_ENTITY) REPEAT_ENTITY(20)  
#define RR_REPEAT21(REPEAT_ENTITY) RR_REPEAT20(REPEAT_ENTITY) REPEAT_ENTITY(21)  
#define RR_REPEAT22(REPEAT_ENTITY) RR_REPEAT21(REPEAT_ENTITY) REPEAT_ENTITY(22)  
#define RR_REPEAT23(REPEAT_ENTITY) RR_REPEAT22(REPEAT_ENTITY) REPEAT_ENTITY(23)  
#define RR_REPEAT24(REPEAT_ENTITY) RR_REPEAT23(REPEAT_ENTITY) REPEAT_ENTITY(24)  
#define RR_REPEAT25(REPEAT_ENTITY) RR_REPEAT24(REPEAT_ENTITY) REPEAT_ENTITY(25)  
#define RR_REPEAT26(REPEAT_ENTITY) RR_REPEAT25(REPEAT_ENTITY) REPEAT_ENTITY(26)  
#define RR_REPEAT27(REPEAT_ENTITY) RR_REPEAT26(REPEAT_ENTITY) REPEAT_ENTITY(27)  
#define RR_REPEAT28(REPEAT_ENTITY) RR_REPEAT27(REPEAT_ENTITY) REPEAT_ENTITY(28)  
#define RR_REPEAT29(REPEAT_ENTITY) RR_REPEAT28(REPEAT_ENTITY) REPEAT_ENTITY(29)  
#define RR_REPEAT30(REPEAT_ENTITY) RR_REPEAT29(REPEAT_ENTITY) REPEAT_ENTITY(30)  
#define RR_REPEAT31(REPEAT_ENTITY) RR_REPEAT30(REPEAT_ENTITY) REPEAT_ENTITY(31)  

#endif
